### ISSUE TITLE
雙引號位置偏了

### ISSUE THREAD

**Issue by imdennis** [tommy60703/the-swift-programming-language-in-traditional-chinese#11]
![2015-01-27 2 45 16](https://cloud.githubusercontent.com/assets/10713328/5905909/96957f40-a5ce-11e4-88ff-146a92a5e750.png)

不知道為何 雙引號位置 錯了
但是複製的內容卻是正確的

**Comment by tommy60703** [comment]
應該是 gitbook 在 render 的時候出錯了
現在看是正常了
Thx~
